export const MEDIA_TYPES = "MEDIA_TYPES";
export const USER_ACCOUNT = "USER_ACCOUNT";
export const SEARCH_ACCOUNT = "SEARCH_ACCOUNT";
export const USER_PROFILE = "USER_PROFILE";
export const SEARCHED_PROFILE = "SEARCHED_PROFILE";
//Publications
export const GET_RECENT_PUBLICATIONS = "GET_RECENT_PUBLICATIONS";
// Followers
export const GET_RECENT_FOLLOWERS = "GET_RECENT_FOLLOWERS";
export const GET_RECENT_FOLLOWINGS = "GET_RECENT_FOLLOWINGS";
export const GET_RECENT_NOTIFICATIONS = "GET_RECENT_NOTIFICATIONS";
export const GET_PENDING_FOLLOWERS_REQUEST = "GET_PENDING_FOLLOWERS_REQUEST";
export const GET_NFT_COLLECTIONS = "GET_NFT_COLLECTIONS";
export const GET_SEARCHED_PROFILE = "GET_SEARCHED_PROFILE";
export const GET_POPUP_STATE = "GET_POPUP_STATE";
export const GET_LIVE_STREAM_DATA = "GET_LIVE_STREAM_DATA";
export const GET_ON_CHAIN_ID = "GET_ON_CHAIN_ID";